version: '3.7'

services:
  kafka:
    restart: always
    image: whatwewant/kafka:${SERVICE_KAFKA_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_KAFKA_PORT}:9092
    environment:
      KAFKA_INTER_BROKER_USER: ${SERVICE_KAFKA_INTER_BROKER_USER}
      KAFKA_INTER_BROKER_PASSWORD: ${SERVICE_KAFKA_INTER_BROKER_PASSWORD}
      ALLOW_PLAINTEXT_LISTENER: yes
      
networks:
  default:
    external: true
    name: compose-ingress
